apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hexo
  name: hexo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hexo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hexo
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/aoxn/blog:0.1-53aec2a
        imagePullPolicy: IfNotPresent
        name: blog
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hexo
  name: hexo
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4000
  selector:
    app: hexo
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hexo
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hexo
            port:
              number: 80
  - host: hexo.wdrip.cn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hexo
            port:
              number: 80
  ingressClassName: nginx
